### ISSUE TITLE
Замечания по паттерну "Стратегия"

### ISSUE THREAD

**Issue by alexey-malov** [alisa-teplouhova/ood2016#1]
В проекте лучше не совмещать разделение по header/source files с разделением по функциональном назначению. То есть header-ы лучше вместе с cpp-шниками в папочках хранить - так будет их легче искать

**Comment by alexey-malov** [comment]
виртуальный деструктор в классе наследнике для экономии места можно не создавать, поскольку он уже был объявлен в родительском классе

**Comment by alexey-malov** [comment]
В заголовочных файлах using namespace использовать не надо.
Вот почему:
http://stackoverflow.com/questions/5849457/using-namespace-in-c-headers

**Comment by alexey-malov** [comment]
пустые конструкторы по умолчанию в интерфейсах можно не писать, т.к. компилятор сгенерирует его сам

**Comment by alexey-malov** [comment]
задание 1. k=0,9
задание 2. k=0.9

**Comment by alexey-malov** [comment]
задание 3. не компилируется - не хватает файлов в репозитории

```
1>c1xx : fatal error C1083: Cannot open source file: 'FlyBehavior.cpp': No such file or directory
1>c1xx : fatal error C1083: Cannot open source file: 'DanceBehavior.cpp': No such file or directory
```

**Comment by alisa-efremova** [comment]
Спасибо, замечания поправила
