### ISSUE TITLE
Замечания по Weather Station

### ISSUE THREAD

**Issue by alexey-malov** [alisa-teplouhova/ood2016#3]
- [x] Использовать UpperCamelCase в именах функций и методов

**Comment by alexey-malov** [comment]
```c++
		for (auto it = m_observers.begin(); it != m_observers.end(); ++it)
		{
			if (it->first > priority)
			{
				m_observers.insert(it, std::make_pair(priority, &observer));
				isObserverSaved = true;
				break;
			}
		}
```

- [x] попробовать использовать алгоритм stl или boost вместо цикла

**Comment by alexey-malov** [comment]
- [x] В базовом Observable не должно быть location, специфичного для дочерних классов. Для идентификации передавайте в данных о событии указатель на соотв. WeatherData

**Comment by alexey-malov** [comment]
- [x] Тип, предоставляющий информацию о виде уведомления сделать параметром шаблона. Тогда можно будет использовать enum или string.

**Comment by alexey-malov** [comment]
- [ ] Версию с сигналами лучше реализовать путем добавления нескольких методов 
```
DoOnTemperatureChange(signal<void(double t)>::slot_type const & handler);
```
и т.п.

В тестах использовать лямбду

```c++
	double expectedTemp = 43;
	bool tempChanged = false;
	wdOut.DoOnTemperatureChange([&](double t){
		BOOST_CHECK(t == expectedTemp);
		tempChanged = true;
	});
	wdOut.SetMeasurements(expectedTemp, 100, 760, 3, 0);
	BOOST_CHECK(tempChanged); tempChanged = false;
	wdOut.SetMeasurements(expectedTemp, 101, 763, 2, 3);
	BOOST_CHECK(!tempChanged);
```

**Comment by alexey-malov** [comment]
- [x] прояснить вопрос с порядком сравнения optional-значений. set требует операцию < для сравнения элементов.

**Comment by alisa-efremova** [comment]
The optional object containing no value is compared less than any value of T. To illustrate this, if the default ordering of size_t is {0, 1, 2, ...}, the default ordering of optional<size_t> is {boost::none, 0, 1, 2, ...}.
