### ISSUE TITLE
Замечания по паттерну "команда"

### ISSUE THREAD

**Issue by alexey-malov** [alisa-teplouhova/ood2016#4]
- [x] При сохранении в html текст должен проходить через кодирование html-сущностей: < > & "

**Comment by alexey-malov** [comment]
- [x] При сохранении документа надо для изображений генерировать уникальные имена, чтобы не перезаписать в выходной папке файлы с одним и тем же именем

**Comment by alexey-malov** [comment]
```c++
void CResizeImageCommand::DoExecute()
{
	SwapUnsigned(m_height, m_newHeight);
}
```

- [x] std::swap работает не хуже

**Comment by alexey-malov** [comment]
```c++
	CDocumentItem(IParagraphPtr paragraph);
	CDocumentItem(IImagePtr image);
```

- [x] shared_ptr лучше передавать по const reference

**Comment by alexey-malov** [comment]
```c++
CImage::~CImage()
{
	fs::remove(m_tempPath);
}
```

- [x] remove может выбросить исключение. поэтому лучше обернуть в try/catch

**Comment by alexey-malov** [comment]
- [x] Устранить дублирование кода в тестах Document

**Comment by alexey-malov** [comment]
- [x] Title должен тоже html-энкодиться

**Comment by alisa-efremova** [comment]
Поправила в коммите
https://github.com/alisa-teplouhova/ood2016/commit/94a51fe0d5919a811e8dc051e66a973cf41384b7
